version: "3.9"

services:

  front:
    build: ./front-joint-purchase/
    ports:
      - "5050:80"
    networks:
      - joint_purchase_network
    depends_on:
      - main_service
      - registration_service

  main_service:
    build: ./joint-purchase/
    ports:
      - "8081:8081"
    networks:
      - joint_purchase_network
    depends_on:
      - postgres
      - minio

  registration_service:
    build: ./joint-purchase-security/
    ports:
      - "8082:8082"
    networks:
      - joint_purchase_network
    depends_on:
      - postgres

  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=joint-purchase'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5433:5432"
    volumes:
      - postgresql:/var/lib/postgresql/
    networks:
      - joint_purchase_network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    networks:
      - joint_purchase_network

networks:
  joint_purchase_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  postgresql: { }
  minio_data:
    driver: local